### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Atzkaaa** [MehulKhanna/PokeGrinder#10]
I really don't know what is happening, but when I execute PokeGrinder.exe it doesn't work.

![image](https://user-images.githubusercontent.com/61913056/200189283-70d991e6-1350-49d2-a720-c18e3cb7c0a2.png)

**Desktop (please complete the following information):**

**Comment by somepepsi** [comment]
Hi, just install that lib.
for ex.: pip install IPython

**Comment by somepepsi** [comment]
> I really don't know what is happening, but when I execute PokeGrinder.exe it doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/61913056/200189283-70d991e6-1350-49d2-a720-c18e3cb7c0a2.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]

Hi, just install that lib.
for ex.: pip install IPython

**Comment by Atzkaaa** [comment]
![image](https://user-images.githubusercontent.com/61913056/201917445-724fc179-a717-4af5-9c33-1e7ac92914a3.png)
Hi, It now show this

**Comment by MehulKhanna** [comment]
> ![image](https://user-images.githubusercontent.com/61913056/201917445-724fc179-a717-4af5-9c33-1e7ac92914a3.png) Hi, It now show this

Hello, can you please download CaptchaSolver.pt from the releases and move it to the assets folder in the PokeGrinder folder.

**Comment by somepepsi** [comment]
> ![image](https://user-images.githubusercontent.com/61913056/201917445-724fc179-a717-4af5-9c33-1e7ac92914a3.png) Hi, It now show this

Try to follow this...
Download CaptchaSolver.pt from https://github.com/MehulKhanna/PokeGrinder/raw/master/assets/CaptchaSolver.pt and move it into the assets folder in the unzipped folder.

**Comment by Atzkaaa** [comment]
It works now, thanks so much!!
