### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by Nozmic** [MehulKhanna/PokeGrinder#11]
![image](https://user-images.githubusercontent.com/118382434/206859968-e383b526-eb41-4cac-9eda-ad8d3c78e945.png)

**Comment by Nozmic** [comment]
I get that error and it closes automatically

**Comment by Nozmic** [comment]
![image](https://user-images.githubusercontent.com/118382434/206875014-91ce170e-63bb-4020-88a1-1329f0f0efaa.png)
I did pip install IPython and it still gives me this error

**Comment by alien18075** [comment]
hello im also currently getting the same issue even after install IPython has there been a fix?

**Comment by Nozmic** [comment]
Hi, nope, still doesn't work for me. Please let me know if you find out a way to fix it.

**Comment by lufy20106** [comment]
@alien18075 and @Nozmic u can try https://github.com/lufy20106/PokeGrinder-V2

**Comment by crazystle** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/1cf93074-656d-4b94-8a1f-a56ce842ca15)

I got this error when the captcha appeared (then I had to solve it myself) and can you help me fix it? I am using version 1.2

**Comment by lufy20106** [comment]
> ![image](https://private-user-images.githubusercontent.com/148273656/285575659-1cf93074-656d-4b94-8a1f-a56ce842ca15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDUzNjcsIm5iZiI6MTcwMDkwNTA2NywicGF0aCI6Ii8xNDgyNzM2NTYvMjg1NTc1NjU5LTFjZjkzMDc0LTY1NmQtNGI5NC04YTFmLWE1NmNlODQyY2ExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwOTM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODU1MDBmMWNmODBiYjQ5NDBiY2Y4NGFiMzE4MDZmNGNjNjk2NTY2NzVkODA2MjY4Y2U5NDc4Y2Y2OTRiMGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SQCCs3LWOdw2LfMqcYwat6PHItYTZLz3KDhoqFETt9c)
> 
> I got this error when the captcha appeared (then I had to solve it myself) and can you help me fix it? I am using version 1.2

v1.2 is dead
use release or mine: [PokeGrinder-V2(python)](https://github.com/lufy20106/PokeGrinder-V2-python)

**Comment by crazystle** [comment]
> > ![image](https://private-user-images.githubusercontent.com/148273656/285575659-1cf93074-656d-4b94-8a1f-a56ce842ca15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDUzNjcsIm5iZiI6MTcwMDkwNTA2NywicGF0aCI6Ii8xNDgyNzM2NTYvMjg1NTc1NjU5LTFjZjkzMDc0LTY1NmQtNGI5NC04YTFmLWE1NmNlODQyY2ExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwOTM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODU1MDBmMWNmODBiYjQ5NDBiY2Y4NGFiMzE4MDZmNGNjNjk2NTY2NzVkODA2MjY4Y2U5NDc4Y2Y2OTRiMGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SQCCs3LWOdw2LfMqcYwat6PHItYTZLz3KDhoqFETt9c)
> > I got this error when the captcha appeared (then I had to solve it myself) and can you help me fix it? I am using version 1.2
> 
> v1.2 is dead use release or mine: [PokeGrinder-V2(python)](https://github.com/lufy20106/PokeGrinder-V2-python)

![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/38209b68-7c21-4c69-99e8-5cb6090eac7d)

i am using your v2 version and sometimes it gives error like this and stops catching pokemon, can you fix it
