### ISSUE TITLE
HTTP 400 Bad Request

### ISSUE THREAD

**Issue by not-toto** [MehulKhanna/PokeGrinder#20]
```
Starting sessions...
 error while opening connection, websocket: close 4004: Authentication failed.
totoyum error while unmarshalling application command index, json: cannot unmarshal number into Go struct field .application_commands.options.choices.value of type string
<mydiscordusername>#0 has started grinding!
PokeGrinder is running, press CTRL+C to exit!
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
^CHTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}

```
Hello, I am getting the above error whenever I try to execute the file. This happens on both windows and linux.

**Comment by MehulKhanna** [comment]
> ```
> Starting sessions...
>  error while opening connection, websocket: close 4004: Authentication failed.
> totoyum error while unmarshalling application command index, json: cannot unmarshal number into Go struct field .application_commands.options.choices.value of type string
> <mydiscordusername>#0 has started grinding!
> PokeGrinder is running, press CTRL+C to exit!
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> ^CHTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"\" is not snowflake."}]}}}
> ```
> 
> Hello, I am getting the above error whenever I try to execute the file. This happens on both windows and linux.

Can you please check if your channelid is correct in the config.json

**Comment by not-toto** [comment]
`{
  "Clients": [
    {
      "Token": "TOKEN",
      "ChannelID": "973161638758854680",
      "FishChannelID": "",
      "Hunting": true,
      "Fishing": false,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "gb",
        "Rare": "ub",
        "Super Rare": "ub",
        "Legendary": "db",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 50,
        "gb": 25,
        "ub": 5,
        "mb": 0
      }
    },
    {
      "Token": "",
      "ChannelID": "",
      "FishChannelID": "",
      "Hunting": true,
      "Fishing": true,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "gb",
        "Rare": "ub",
        "Super Rare": "ub",
        "Legendary": "db",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 50,
        "gb": 25,
        "ub": 5,
        "mb": 1
      }
    }
  ]
}`

**Comment by not-toto** [comment]
It works, thanks.

**Comment by not-toto** [comment]
It works, thanks.
