### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SANKETOP** [MehulKhanna/PokeGrinder#22]
It's giving this kind of error in mobile termux app
![Uploading Screenshot_2023-12-18-21-59-25-464_com.termux-edit.jpg…]()

**Comment by SANKETOP** [comment]
I have set the second token one hunting and fishing false

**Comment by MehulKhanna** [comment]
> I have set the second token one hunting and fishing false

Send config please (hiding tokens)

**Comment by SANKETOP** [comment]
{
  "Clients": [
    {
      "Token": "TOKEN",
      "ChannelID": "932591514188677170",
      "FishChannelID": "",
      "Hunting": true,
      "Fishing": false,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "ub",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 15,
        "gb": 7,
        "ub": 4,
        "mb": 0
      }
    },
    {
      "Token": "",
      "ChannelID": "",
      "FishChannelID": "",
      "Hunting": false,
      "Fishing": false,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "gb",
        "Rare": "ub",
        "Super Rare": "ub",
        "Legendary": "db",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 50,
        "gb": 25,
        "ub": 5,
        "mb": 0
      }
    }
  ]
}

**Comment by SANKETOP** [comment]
> > I have set the second token one hunting and fishing false
> 
> Send config please (hiding tokens)




{
  "Clients": [
    {
      "Token": "TOKEN",
      "ChannelID": "932591514188677170",
      "FishChannelID": "",
      "Hunting": true,
      "Fishing": false,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "ub",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 15,
        "gb": 7,
        "ub": 4,
        "mb": 0
      }
    },
    {
      "Token": "",
      "ChannelID": "",
      "FishChannelID": "",
      "Hunting": false,
      "Fishing": false,
      "Balls": {
        "Common": "pb",
        "Uncommon": "pb",
        "Rare": "gb",
        "Super Rare": "ub",
        "Legendary": "mb",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "FishBalls": {
        "Common": "pb",
        "Uncommon": "gb",
        "Rare": "ub",
        "Super Rare": "ub",
        "Legendary": "db",
        "Shiny": "mb",
        "Shiny Event": "mb",
        "Shiny Full-odds": "prb"
      },
      "AutoBuy": {
        "pb": 50,
        "gb": 25,
        "ub": 5,
        "mb": 0
      }
    }
  ]
}

**Comment by SANKETOP** [comment]
I fixed that problem but getting another error

**Comment by SANKETOP** [comment]
Starting sessions...
89216512#0 has started grinding!
PokeGrinder is running, press CTRL+C to exit!
89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]

goroutine 72 [running]:
main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0)
        /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24
github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?})
        /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44
created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52
        /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c
exit status 2

**Comment by MehulKhanna** [comment]
> Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> 
> goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2

Does this occur every time you start the bot?

**Comment by SANKETOP** [comment]
> > Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> > goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2
> 
> Does this occur every time you start the bot? Also, please ensure there are no bots other than Pokemeow in the server you are grinding in.

Yes after catching 2 to 3 pokemons I found this error and there is no other bots in the server except pokemeow

**Comment by MehulKhanna** [comment]
> > > Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> > > goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2
> > 
> > 
> > Does this occur every time you start the bot? Also, please ensure there are no bots other than Pokemeow in the server you are grinding in.
> 
> Yes after catching 2 to 3 pokemons I found this error and there is no other bots in the server except pokemeow

Seems like a termux problem as I am unable to reproduce this issue.

**Comment by MehulKhanna** [comment]
> > > Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> > > goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2
> > 
> > 
> > Does this occur every time you start the bot? Also, please ensure there are no bots other than Pokemeow in the server you are grinding in.
> 
> Yes after catching 2 to 3 pokemons I found this error and there is no other bots in the server except pokemeow

Can you start the bot and then me screenshots of the messages in the discord channel?

**Comment by SANKETOP** [comment]
> > > > Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> > > > goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2
> > > 
> > > 
> > > Does this occur every time you start the bot? Also, please ensure there are no bots other than Pokemeow in the server you are grinding in.
> > 
> > 
> > Yes after catching 2 to 3 pokemons I found this error and there is no other bots in the server except pokemeow
> 
> Seems like a termux problem as I am unable to reproduce this issue.

I also tried it in pc same error coming

**Comment by SANKETOP** [comment]
> > > > Starting sessions... 89216512#0 has started grinding! PokeGrinder is running, press CTRL+C to exit! 89216512 | Encounters: 1 | Catches: 1 | Fish Catches: 0 panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5612fd4bb4]
> > > > goroutine 72 [running]: main/instance.WaitForUpdate.func1(0x0?, 0x4000b0cac0) /data/data/com.termux/files/home/PokeGrinder-master/instance/hunting.go:35 +0x24 github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x0?, 0x0?, {0x56130396a0?, 0x4000b0cac0?}) /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x44 created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 52 /data/data/com.termux/files/home/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x14c exit status 2
> > > 
> > > 
> > > Does this occur every time you start the bot? Also, please ensure there are no bots other than Pokemeow in the server you are grinding in.
> > 
> > 
> > Yes after catching 2 to 3 pokemons I found this error and there is no other bots in the server except pokemeow
> 
> Can you start the bot and then me screenshots of the messages in the discord channel?

In discord channel it's working in cmd prompt/termux it's giving rrror
