### ISSUE TITLE
Error 4004 / 404 Fishing channel not found

### ISSUE THREAD

**Issue by Filmrundung** [MehulKhanna/PokeGrinder#23]
**Describe the bug**
Hello i installed the bot and filled out everything but it says he finds no fishing channels. Both channels linked are in different servers and both servers only have pokemeow bot 

![Bild_2023-12-19_181955101](https://github.com/MehulKhanna/PokeGrinder/assets/74430310/17bd36bc-3ede-4263-ae2a-4fa2efe71414)

**Comment by Filmrundung** [comment]
> > **Describe the bug** Hello i installed the bot and filled out everything but it says he finds no fishing channels. Both channels linked are in different servers and both servers only have pokemeow bot
> > ![Bild_2023-12-19_181955101](https://private-user-images.githubusercontent.com/74430310/291664328-17bd36bc-3ede-4263-ae2a-4fa2efe71414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDcwMDEsIm5iZiI6MTcwMzAwNjcwMSwicGF0aCI6Ii83NDQzMDMxMC8yOTE2NjQzMjgtMTdiZDM2YmMtM2VkZS00MjYzLWFlMmEtNGZhMmVmZTcxNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE3MjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYzgyMDAyNDhjN2MwMjBkZjI3MGZmYzVkOTI2MGZjZTJjZjVjOGIzZDUyZTlmM2FiOWZiYzZhY2VlMWE1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FP9ouIPlKYFEFBUoh_j4-DxYcccN6gEw1ysHdJOvksM)
> 
> the channel IDs must be enclosed with "" Like so :- "ChannelID": "1065293736272922",

thank you, solved it but theres another problem now. The program always closes itself after a short time and in the beginning theres a error:
![Bild_2023-12-19_191227547](https://github.com/MehulKhanna/PokeGrinder/assets/74430310/907c59c2-72e0-4d32-8630-c6c879329bff)

**Comment by MehulKhanna** [comment]
> > > **Describe the bug** Hello i installed the bot and filled out everything but it says he finds no fishing channels. Both channels linked are in different servers and both servers only have pokemeow bot
> > > ![Bild_2023-12-19_181955101](https://private-user-images.githubusercontent.com/74430310/291664328-17bd36bc-3ede-4263-ae2a-4fa2efe71414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDcwMDEsIm5iZiI6MTcwMzAwNjcwMSwicGF0aCI6Ii83NDQzMDMxMC8yOTE2NjQzMjgtMTdiZDM2YmMtM2VkZS00MjYzLWFlMmEtNGZhMmVmZTcxNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE3MjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYzgyMDAyNDhjN2MwMjBkZjI3MGZmYzVkOTI2MGZjZTJjZjVjOGIzZDUyZTlmM2FiOWZiYzZhY2VlMWE1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FP9ouIPlKYFEFBUoh_j4-DxYcccN6gEw1ysHdJOvksM)
> > 
> > 
> > the channel IDs must be enclosed with "" Like so :- "ChannelID": "1065293736272922",
> 
> thank you, solved it but theres another problem now. The program always closes itself after a short time and in the beginning theres a error: ![Bild_2023-12-19_191227547](https://private-user-images.githubusercontent.com/74430310/291676992-907c59c2-72e0-4d32-8630-c6c879329bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjI1NjYsIm5iZiI6MTcwMzI2MjI2NiwicGF0aCI6Ii83NDQzMDMxMC8yOTE2NzY5OTItOTA3YzU5YzItNzJlMC00ZDMyLTg2MzAtYzZjODc5MzI5YmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2MjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwODgzNmZhZDFiMDQ0NTE2YjZjYjBhNTZhNzI2MmY3YjgyY2I0ZDU2Y2UyZDliNGEyNGViZDU4NWI3OTM0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pjSNLEGFda-gmes9lzK3JAqjRC7rduUIhlWjVVylGZw)

You have either forgotten to put a token in the config or your token is wrong. Please get your token again and then try.

**Comment by Filmrundung** [comment]
but it works on my accounts it just sometimes grinds 1sec sometimes 10s and sometimes a minute but it closes more often on 1 specific acc

**Comment by Filmrundung** [comment]
Bro when i start it through cmd it says error when unmarshalling (both json ) unexpected end of JSON input
starting sessions….
Pokegrinder is running, press CTRL + C to exit! 

But it doesnt grind.

When i start it by opening the .exe normally it grinds for a few seconds and then closes.

Can u help me with that?

**Comment by MehulKhanna** [comment]
> Bro when i start it through cmd it says error when unmarshalling (both json ) unexpected end of JSON input starting sessions…. Pokegrinder is running, press CTRL + C to exit!
> 
> But it doesnt grind.
> 
> When i start it by opening the .exe normally it grinds for a few seconds and then closes.
> 
> Can u help me with that?

Can you paste the error from cmd here

**Comment by Filmrundung** [comment]
Sorry i just opened it wrong the error isnt showing up anymore but now i have the same problem with cmd as opening normal it hunts a few times and then closes. Is the Captcha solver neccessary ? Cause i dont use it maybe thats the problem

**Comment by MehulKhanna** [comment]
> Sorry i just opened it wrong the error isnt showing up anymore but now i have the same problem with cmd as opening normal it hunts a few times and then closes. Is the Captcha solver neccessary ? Cause i dont use it maybe thats the problem

It is necessary right now but I can later add an option to use without running captcha solver.

**Comment by MehulKhanna** [comment]
> Sorry i just opened it wrong the error isnt showing up anymore but now i have the same problem with cmd as opening normal it hunts a few times and then closes. Is the Captcha solver neccessary ? Cause i dont use it maybe thats the problem

Also, I have recently pushed a new release please make sure you use the new executables now.

**Comment by Filmrundung** [comment]
Hm i installed the new executable but its not even opening anymore.
Not over cmd and not normal

**Comment by Filmrundung** [comment]
Nvm thank you the problems are fixed i just had to use the solver
