### ISSUE TITLE
When i run the executable file for my windows system, it automatically close

### ISSUE THREAD

**Issue by imkhoa19032110** [MehulKhanna/PokeGrinder#25]
please help

**Comment by MehulKhanna** [comment]
> please help

Have you started the captcha solver first?

**Comment by imkhoa19032110** [comment]
yeah

**Comment by imkhoa19032110** [comment]
and keep the captcha solver open and run the exe file but it always close

**Comment by imkhoa19032110** [comment]
1. I downloaded the responsity
2. I put the token, the channel/user id for 1 account 
3. I download captcha.pt file and put it into the folder where has captcha solver.py 
4. I used the command you gave to run the captchasolver.py and keep it open
5. I downloaded the exe file and put it into that folder
6. I ran the exe file and it keeps close

**Comment by MehulKhanna** [comment]
> 1. I downloaded the responsity
> 2. I put the token, the channel/user id for 1 account
> 3. I download captcha.pt file and put it into the folder where has captcha solver.py
> 4. I used the command you gave to run the captchasolver.py and keep it open
> 5. I downloaded the exe file and put it into that folder
> 6. I ran the exe file and it keeps close

Did you put fishes.json as well?

**Comment by imkhoa19032110** [comment]
should i try to install pytorch or anything else ?

> > 1. I downloaded the responsity
> > 2. I put the token, the channel/user id for 1 account
> > 3. I download captcha.pt file and put it into the folder where has captcha solver.py
> > 4. I used the command you gave to run the captchasolver.py and keep it open
> > 5. I downloaded the exe file and put it into that folder
> > 6. I ran the exe file and it keeps close
> 
> Did you put fishes.json as well?

yes, should i try to install anything like pytorch ?

**Comment by MehulKhanna** [comment]
> should i try to install pytorch or anything else ?
> 
> > > 1. I downloaded the responsity
> > > 2. I put the token, the channel/user id for 1 account
> > > 3. I download captcha.pt file and put it into the folder where has captcha solver.py
> > > 4. I used the command you gave to run the captchasolver.py and keep it open
> > > 5. I downloaded the exe file and put it into that folder
> > > 6. I ran the exe file and it keeps close
> > 
> > 
> > Did you put fishes.json as well?
> 
> yes, should i try to install anything like pytorch ?

Can you try running the exe from the terminal using `./PokeGrinder-windows64.exe`

**Comment by imkhoa19032110** [comment]
no i ran it and it closed

**Comment by MehulKhanna** [comment]
> should i try to install pytorch or anything else ?
> 
> > > 1. I downloaded the responsity
> > > 2. I put the token, the channel/user id for 1 account
> > > 3. I download captcha.pt file and put it into the folder where has captcha solver.py
> > > 4. I used the command you gave to run the captchasolver.py and keep it open
> > > 5. I downloaded the exe file and put it into that folder
> > > 6. I ran the exe file and it keeps close
> > 
> > 
> > Did you put fishes.json as well?
> 
> yes, should i try to install anything like pytorch ?

Can 

> no i ran it and it closed

Does it give any errors?

**Comment by imkhoa19032110** [comment]
no, it closed instant

**Comment by imkhoa19032110** [comment]
let em give you a picture

**Comment by imkhoa19032110** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/c1e11292-5372-421b-b674-e8023a5c2e3d)
is this right ?

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/292620925-c1e11292-5372-421b-b674-e8023a5c2e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjcxNjEsIm5iZiI6MTcwMzMyNjg2MSwicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjIwOTI1LWMxZTExMjkyLTUzNzItNDIxYi1iNjc0LWU4MDIzYTVjMmUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMDIxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGY2OGU2OTBlYjEyYjU1NDk0MWYxNjAyZTYyNTU3ODcyOGQxYjJiNmJiOGNkOWFmZGQ0OWI1MDVkMTNiMmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iz2uBwgXL9yWtbAAAeLRUEH00PNSe7DqoC_UhUvy-OE) is this right ?

Yes

**Comment by imkhoa19032110** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/54a63542-5977-40da-ba1b-2eff9eef044c)
the error here

**Comment by MehulKhanna** [comment]
> > ![image](https://private-user-images.githubusercontent.com/142767777/292620925-c1e11292-5372-421b-b674-e8023a5c2e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjcxNjEsIm5iZiI6MTcwMzMyNjg2MSwicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjIwOTI1LWMxZTExMjkyLTUzNzItNDIxYi1iNjc0LWU4MDIzYTVjMmUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMDIxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGY2OGU2OTBlYjEyYjU1NDk0MWYxNjAyZTYyNTU3ODcyOGQxYjJiNmJiOGNkOWFmZGQ0OWI1MDVkMTNiMmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iz2uBwgXL9yWtbAAAeLRUEH00PNSe7DqoC_UhUvy-OE) is this right ?
> 
> Yes

You have to try running it from terminal as it will show errors in the terminal. Open a terminal and put command ./PokeGrinder-windows64.exe

**Comment by imkhoa19032110** [comment]
i did it

**Comment by MehulKhanna** [comment]
> i did it

Then what is the output in the terminal?

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/292621084-6039bc8e-9afe-4a9c-bda3-1350effc5c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjczMDUsIm5iZiI6MTcwMzMyNzAwNSwicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjIxMDg0LTYwMzliYzhlLTlhZmUtNGE5Yy1iZGEzLTEzNTBlZmZjNWM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMDIzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTU3ODc0NDczMTJjNzk0NjJiNWI2NGVmMjE2NDkxMjE2MTRiMjVhZTM4NzNiZmIyODdkZTMwY2JjMTM5NWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x9S_w7QNBQLjyLS9wMWzp7vYHMciwdBT3umeDEL6www) the error here

Oh

**Comment by MehulKhanna** [comment]
Try running again

**Comment by imkhoa19032110** [comment]
nah it always have that error

**Comment by MehulKhanna** [comment]
> nah it always have that error

Are you in a server with pokemeow only and no other bot?

**Comment by imkhoa19032110** [comment]
no let me do it

**Comment by imkhoa19032110** [comment]
omg its worked thanks
