### ISSUE TITLE
new error :((

### ISSUE THREAD

**Issue by imkhoa19032110** [MehulKhanna/PokeGrinder#27]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/0dc3a005-1713-4573-b757-feb6e7b0af51)
help

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/292621672-0dc3a005-1713-4573-b757-feb6e7b0af51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjgxMTMsIm5iZiI6MTcwMzMyNzgxMywicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjIxNjcyLTBkYzNhMDA1LTE3MTMtNDU3My1iNzU3LWZlYjZlN2IwYWY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMDM2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzdjZTQzMDc0NWFiZjllM2RhOTAwMTdjODgxMDdlZTMwZGRiMTljYzVkZGE5ZjhjNGQ4OTFkY2JmNzViM2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZHmFkHh4WNYfmSdojGVXIvAC0K-6aHMunumTfCXjFg) help

Retry

**Comment by imkhoa19032110** [comment]
it happened again

**Comment by MehulKhanna** [comment]
> it happened again

Keep trying

**Comment by imkhoa19032110** [comment]
do you know how to fix it

**Comment by MehulKhanna** [comment]
> do you know how to fix it

Fixing

**Comment by imkhoa19032110** [comment]
its always happend to me if you fixed it, let me know

**Comment by MehulKhanna** [comment]
> its always happend to me if you fixed it, let me know

I have fixed the bug. Just replace your executable file with a new one from the new release.

**Comment by imkhoa19032110** [comment]
ok

**Comment by imkhoa19032110** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/532d5494-9052-4847-aa8d-c4061aedf5c4)
it happened again
