### ISSUE TITLE
again

### ISSUE THREAD

**Issue by imkhoa19032110** [MehulKhanna/PokeGrinder#28]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/bc38b145-cd1f-4cf2-a6c9-297b550729c1)
help

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/292623316-bc38b145-cd1f-4cf2-a6c9-297b550729c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzE3OTAsIm5iZiI6MTcwMzMzMTQ5MCwicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjIzMzE2LWJjMzhiMTQ1LWNkMWYtNGNmMi1hNmM5LTI5N2I1NTA3MjljMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMTM4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjEwNmU0ZWMyYTkyOWFhYjgwZDA2Mzg1MTMzOTlkNmUyYWI0ODAxOGUyMTVmZjBkODM1OGI0YzljYTFiNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kyF8-78GL6-iNbdH6itZgvtjqeOcipsd40muKa4LHV4) help

please send image of the messages from your grinding channel when this occured.

**Comment by imkhoa19032110** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/5b691076-17c1-41d5-ac22-ee3fef4c02db)
are you here ?

**Comment by imkhoa19032110** [comment]
when i turn of the autofish = false, it doesnt appear error anymore, you must change the cooldown of fishing commands, i think you can fix it by doing it

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/292651518-5b691076-17c1-41d5-ac22-ee3fef4c02db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Njk5NzYsIm5iZiI6MTcwMzY2OTY3NiwicGF0aCI6Ii8xNDI3Njc3NzcvMjkyNjUxNTE4LTViNjkxMDc2LTE3YzEtNDFkNS1hYzIyLWVlM2ZlZjRjMDJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwOTM0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjQ3NTZiMzRhMTExMjMyYjA3OTk3NDYyZmE3Yjg0MmU3NDU2YjY0MWNlMjhmZTU0ZmE5NWFlYTQ2MDhmMDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9jME00kbzE9ad0dmn_cmxUaHksJE6_kTjaMVvAZIeEo) are you here ?

Your fishing and hunting channels are the same. Please read the readme carefully before creating an issue.
