### ISSUE TITLE
not solving captcha

### ISSUE THREAD

**Issue by SANKETOP** [MehulKhanna/PokeGrinder#30]
Not solving captcha i get ban
![image](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/6e8f293f-f70c-4f3c-b555-1f3cb070ac9a)

**Comment by MehulKhanna** [comment]
> Not solving captcha i get ban ![image](https://private-user-images.githubusercontent.com/91170563/292657206-6e8f293f-f70c-4f3c-b555-1f3cb070ac9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzAxNTUsIm5iZiI6MTcwMzY2OTg1NSwicGF0aCI6Ii85MTE3MDU2My8yOTI2NTcyMDYtNmU4ZjI5M2YtZjcwYy00ZjNjLWI1NTUtMWYzY2IwNzBhYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGExYWJkMzQ3ZTkwYmNmOWNmOGJhOTU5NjY2NzgxYjMzNTU0Mzk0NDFjNzUyN2ZjNTE2MDkwZTRhYTVhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5QlXot4qfjxMw2iN3IbKhvum5cgIzTvXJE0dH83rwM)

Please provide some more information while creating an issue. Just an image with a sentence is obviously not enough.

**Comment by SANKETOP** [comment]
> > Not solving captcha i get ban ![image](https://private-user-images.githubusercontent.com/91170563/292657206-6e8f293f-f70c-4f3c-b555-1f3cb070ac9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzAxNTUsIm5iZiI6MTcwMzY2OTg1NSwicGF0aCI6Ii85MTE3MDU2My8yOTI2NTcyMDYtNmU4ZjI5M2YtZjcwYy00ZjNjLWI1NTUtMWYzY2IwNzBhYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NGExYWJkMzQ3ZTkwYmNmOWNmOGJhOTU5NjY2NzgxYjMzNTU0Mzk0NDFjNzUyN2ZjNTE2MDkwZTRhYTVhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5QlXot4qfjxMw2iN3IbKhvum5cgIzTvXJE0dH83rwM)
> 
> Please provide some more information while creating an issue. Just an image with a sentence is obviously not enough.

No other error it was working fine suddenly it tries so many number and tried more than 5 times there was no error in cmd prompt

**Comment by SANKETOP** [comment]
Which images will I give u about?

**Comment by MehulKhanna** [comment]
> Which images will I give u about?

Discord channel messages of when this happened
