### ISSUE TITLE
Captcha Solver

### ISSUE THREAD

**Issue by Faust404** [MehulKhanna/PokeGrinder#35]
Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.

Creating an issue because I have no other way to reach out to the repo owners.

**Comment by Faust404** [comment]
> > Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.
> > Creating an issue because I have no other way to reach out to the repo owners.
> 
> It was trained on a dataset of 1.9k images. I first labelled about 200-300 captchas myself and trained a model using those images. Then I used that model to label the rest of the images, making corrections myself wherever necessary. Then I trained a final model with all the 1.9k captchas labelled.
> 
> The model was trained using the YOLOv8x (68,162,238 params) model with a batch size of 16 for 224 epochs and with all the images resized to 320x320 pixels.

Thanks for the reply. I was attempting something like this because I had tried template matching with openCV without much luck.

Were the images grayscaled or any other image processing done before training the model?

**Comment by Bitte0099** [comment]
> > Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.
> > Creating an issue because I have no other way to reach out to the repo owners.
> 
> It was trained on a dataset of 1.9k images. I first labelled about 200-300 captchas myself and trained a model using those images. Then I used that model to label the rest of the images, making corrections myself wherever necessary. Then I trained a final model with all the 1.9k captchas labelled.
> 
> The model was trained using the YOLOv8x (68,162,238 params) model with a batch size of 16 for 224 epochs and with all the images resized to 320x320 pixels.

How is your model well over 500MB but the yolov8x is 131MB only? I trained one based on captcha too (3.4k images~) but it just a little over 134MB.

**Comment by Faust404** [comment]
> > > Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.
> > > Creating an issue because I have no other way to reach out to the repo owners.
> > 
> > 
> > It was trained on a dataset of 1.9k images. I first labelled about 200-300 captchas myself and trained a model using those images. Then I used that model to label the rest of the images, making corrections myself wherever necessary. Then I trained a final model with all the 1.9k captchas labelled.
> > The model was trained using the YOLOv8x (68,162,238 params) model with a batch size of 16 for 224 epochs and with all the images resized to 320x320 pixels.
> 
> How is your model well over 500MB but the yolov8x is 131MB only? I trained one based on captcha too (3.4k images~) but it just a little over 134MB.

What kinda accuracy were you able to obtain with your model. Also any chance you have a link to the dataset and model you trained?

**Comment by MehulKhanna** [comment]
> > > > Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.
> > > > Creating an issue because I have no other way to reach out to the repo owners.
> > > 
> > > 
> > > It was trained on a dataset of 1.9k images. I first labelled about 200-300 captchas myself and trained a model using those images. Then I used that model to label the rest of the images, making corrections myself wherever necessary. Then I trained a final model with all the 1.9k captchas labelled.
> > > The model was trained using the YOLOv8x (68,162,238 params) model with a batch size of 16 for 224 epochs and with all the images resized to 320x320 pixels.
> > 
> > 
> > How is your model well over 500MB but the yolov8x is 131MB only? I trained one based on captcha too (3.4k images~) but it just a little over 134MB.
> 
> What kinda accuracy were you able to obtain with your model. Also any chance you have a link to the dataset and model you trained?

94-95% accuracy. Dataset link https://drive.google.com/drive/folders/1--rPnwhIIn6zMyR3Trl5Z6aUoenp0Px7

**Comment by Faust404** [comment]
> > > > > Curious on what kinda dataset and process was used to train the YOLO model. It works well with over 90% accuracy.
> > > > > Creating an issue because I have no other way to reach out to the repo owners.
> > > > 
> > > > 
> > > > It was trained on a dataset of 1.9k images. I first labelled about 200-300 captchas myself and trained a model using those images. Then I used that model to label the rest of the images, making corrections myself wherever necessary. Then I trained a final model with all the 1.9k captchas labelled.
> > > > The model was trained using the YOLOv8x (68,162,238 params) model with a batch size of 16 for 224 epochs and with all the images resized to 320x320 pixels.
> > > 
> > > 
> > > How is your model well over 500MB but the yolov8x is 131MB only? I trained one based on captcha too (3.4k images~) but it just a little over 134MB.
> > 
> > 
> > What kinda accuracy were you able to obtain with your model. Also any chance you have a link to the dataset and model you trained?
> 
> 94-95% accuracy. Dataset link https://drive.google.com/drive/folders/1--rPnwhIIn6zMyR3Trl5Z6aUoenp0Px7

Thanks for the dataset. I did already get it from lufy who I contacted through discord and I trained my own version of the model as well. I trained a nano model because I wanted to see how small I can go without losing performance and it's performing surprisingly well. I was able to obtain over 95% accuracy with the yolov8n model and it's only 6MB in size. It was trained with 3.2k images.

Maybe you can test the model and let me know how it goes. I have uploaded my dataset and the nano model in that same gdrive link. Also please do check your email, I have contacted you there as well.
