### ISSUE TITLE
error while connecting to captcha solver API

### ISSUE THREAD

**Issue by Atzkaaa** [MehulKhanna/PokeGrinder#37]
I got this message when I try to run 
PokeGrinder-windows64.exe
in CMD

error while connecting to captcha solver API

**Comment by MehulKhanna** [comment]
> I got this message when I try to run PokeGrinder-windows64.exe in CMD
> 
> error while connecting to captcha solver API

![Uploading Screenshot_20240125_230747_Chrome.png…]()

Have you performed these steps before trying to run the exe?

**Comment by Atzkaaa** [comment]
when I try to run uvicorn, it appears:

'uvicorn' is not recognized as an internal or external command, operable program or batch file.

**Comment by MehulKhanna** [comment]
> when I try to run uvicorn, it appears:
> 
> 'uvicorn' is not recognized as an internal or external command, operable program or batch file.

pip install "uvicorn[standard]"
Run this command first and then try

**Comment by Atzkaaa** [comment]
C:\Users\BERNARDO.UEDA\Desktop\PokeGrinder-2.3>pip install "uvicorn[standard]"
Requirement already satisfied: uvicorn[standard] in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.27.0)
Requirement already satisfied: h11>=0.8 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.14.0)
Requirement already satisfied: click>=7.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (8.1.7)
Requirement already satisfied: typing-extensions>=4.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (4.9.0)
Requirement already satisfied: colorama>=0.4 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.4.6)
Requirement already satisfied: websockets>=10.4 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (12.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (6.0.1)
Requirement already satisfied: watchfiles>=0.13 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.21.0)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (1.0.1)
Requirement already satisfied: httptools>=0.5.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.6.1)
Requirement already satisfied: anyio>=3.0.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from watchfiles>=0.13->uvicorn[standard]) (4.2.0)
Requirement already satisfied: idna>=2.8 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (3.6)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (1.2.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (1.3.0)
WARNING: You are using pip version 21.1.1; however, version 23.3.2 is available.
You should consider upgrading via the 'C:\Users\BERNARDO.UEDA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

this was the message afte pip install "uvicorn[standard]"

and It still shows 

'uvicorn' is not recognized as an internal or external command, operable program or batch file.

after i try 
uvicorn CaptchaSolver:app --reload

**Comment by MehulKhanna** [comment]
> C:\Users\BERNARDO.UEDA\Desktop\PokeGrinder-2.3>pip install "uvicorn[standard]" Requirement already satisfied: uvicorn[standard] in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.27.0) Requirement already satisfied: h11>=0.8 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.14.0) Requirement already satisfied: click>=7.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (8.1.7) Requirement already satisfied: typing-extensions>=4.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (4.9.0) Requirement already satisfied: colorama>=0.4 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.4.6) Requirement already satisfied: websockets>=10.4 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (12.0) Requirement already satisfied: pyyaml>=5.1 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (6.0.1) Requirement already satisfied: watchfiles>=0.13 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.21.0) Requirement already satisfied: python-dotenv>=0.13 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (1.0.1) Requirement already satisfied: httptools>=0.5.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from uvicorn[standard]) (0.6.1) Requirement already satisfied: anyio>=3.0.0 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from watchfiles>=0.13->uvicorn[standard]) (4.2.0) Requirement already satisfied: idna>=2.8 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (3.6) Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (1.2.0) Requirement already satisfied: sniffio>=1.1 in c:\users\bernardo.ueda\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from anyio>=3.0.0->watchfiles>=0.13->uvicorn[standard]) (1.3.0) WARNING: You are using pip version 21.1.1; however, version 23.3.2 is available. You should consider upgrading via the 'C:\Users\BERNARDO.UEDA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
> 
> this was the message afte pip install "uvicorn[standard]"
> 
> and It still shows
> 
> 'uvicorn' is not recognized as an internal or external command, operable program or batch file.
> 
> after i try uvicorn CaptchaSolver:app --reload

Did you check the "add python to path" checkbox while installing python?

**Comment by Atzkaaa** [comment]
I figure it out, I still don't know how but it is working now
