### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mido933** [MehulKhanna/PokeGrinder#4]
Heyo,

I might be a clown and too noob for this, but what that step means?

"Inside of the repo type the following command python -m pip install -r requirements.txt"
where to put the command? which file?

**Comment by MehulKhanna** [comment]
> Heyo,
> 
> I might be a clown and too noob for this, but what that step means?
> 
> "Inside of the repo type the following command python -m pip install -r requirements.txt" where to put the command? which file?

It means to open the folder where the main.py file is located and run the command "python -m pip install -r requirements.txt". To run this command after opening the folder you can either click on the path that is shown below the toolbar and contains text like downloads/documents/folder/... and put the command in that box and press enter. Or you can right click inside the opened folder and click open with terminal and paste and run the command in the terminal.

**Comment by mido933** [comment]
if you would just make the bot into an exe for me, i would really really appriciate your time and effort and i would praise you for life. i'm sorry, but ig i'm just too nub for that part. :(

**Comment by MehulKhanna** [comment]
> if you would just make the bot into an exe for me, i would really really appriciate your time and effort and i would praise you for life. i'm sorry, but ig i'm just too nub for that part. :(

I have created the executable and instructions for installing have been updated in the readme. Please let me know if you have any issues running the executable.

**Comment by mido933** [comment]
thats great. tyvm! its working just fine! <3
