### ISSUE TITLE
Possible error in startup.py

### ISSUE THREAD

**Issue by AloW0304** [MehulKhanna/PokeGrinder#41]
After downloading the new update, I think I might've found an error, the document startup.py comes up with this error:
Tuple expression not allowed in type annotation
  Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type
  which is talking about this command here: 
  async def get_commands(bot: commands.Bot, channel_id: int) -> (
    TextChannel,
    dict[str, SlashCommand | UserCommand | MessageCommand | SubCommand] | None,
):

with this line of code here: (
    TextChannel,
    dict[str, SlashCommand | UserCommand | MessageCommand | SubCommand] | None,
):
being broadcast as the problem

**Comment by AloW0304** [comment]
Also thanks so much for the consistent and constant support you are giving to this project, it is greatly appreciated. :)

**Comment by AloW0304** [comment]
The impact of this error causes this error message when running main.py
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 600, in _run_event
    await coro(*args, **kwargs)
  File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 51, in on_ready
    await get_commands(self.bot, self.config.hunting_channel_id)
  File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 31, in get_commands
    for command in await channel.application_commands()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TextChannel' object has no attribute 'application_commands'



Then the Pokegrinder logs and table pop up but nothing happens, eta time increases but no encounters or catches happen

**Comment by MehulKhanna** [comment]
> After downloading the new update, I think I might've found an error, the document startup.py comes up with this error: Tuple expression not allowed in type annotation   Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type   which is talking about this command here:   async def get_commands(bot: commands.Bot, channel_id: int) -> ( TextChannel, dict[str, SlashCommand | UserCommand | MessageCommand | SubCommand] | None, ):
> 
> with this line of code here: ( TextChannel, dict[str, SlashCommand | UserCommand | MessageCommand | SubCommand] | None, ): being broadcast as the problem

Remove this part of the code that is causing the error :-
`-> (
TextChannel,
dict[str, SlashCommand | UserCommand | MessageCommand | SubCommand] | None,
)`

**Comment by AloW0304** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/109468340/9309e496-500c-41bd-9178-225f46d6ad45)
After running, this comes up in the terminal. Nothing is spawned or caught, only the time keeps ticking. There is no more error message now though.

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/109468340/302976071-9309e496-500c-41bd-9178-225f46d6ad45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDk0NDUsIm5iZiI6MTcwNzMwOTE0NSwicGF0aCI6Ii8xMDk0NjgzNDAvMzAyOTc2MDcxLTkzMDllNDk2LTUwMGMtNDFiZC05MTc4LTIyNWY0NmQ2YWQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMjMyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQ3ZmIzNWE0OTQ3MDAxNGIxMTUyOTQ3ZGM2Mzk1NDQwM2NkNzYxNzVhZWQ3NGM2ZGVlMDBiMjZjOWQ0OTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z2ZyHF-NGW9-ULAQb5-SRhSMDyNCwRpleSvAXAiCFQ4) After running, this comes up in the terminal. Nothing is spawned or caught, only the time keeps ticking. There is no more error message now.

Remive this line from modules/logging.py then look for errors
os.system("cls" if os.name == "nt" else "clear")

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/109468340/302976071-9309e496-500c-41bd-9178-225f46d6ad45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjUxOTQsIm5iZiI6MTcwNzMyNDg5NCwicGF0aCI6Ii8xMDk0NjgzNDAvMzAyOTc2MDcxLTkzMDllNDk2LTUwMGMtNDFiZC05MTc4LTIyNWY0NmQ2YWQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxNjU0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjJmM2NiOTM2YTk3NzdhMWUyMDZmNDFhZWVjNWExM2NjYWRkMjUwNmYzYmQwZDlkZTJjY2IzZTczNDQxNWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.04Q5A2k5yiP1Z_XdR6PPkLqXn54DgNLR0mtZpNllNBA) After running, this comes up in the terminal. Nothing is spawned or caught, only the time keeps ticking. There is no more error message now.

I have updated the repository this must be fixed now.

**Comment by AloW0304** [comment]
getting this error now:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 600, in _run_event
    await coro(*args, **kwargs)
  File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 48, in on_ready
    await get_commands(self.bot, self.config.hunting_channel_id)
  File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 28, in get_commands
    for command in await channel.application_commands()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TextChannel' object has no attribute 'application_commands'

which is the same error as before, however now my table looks like this:
![image](https://github.com/MehulKhanna/PokeGrinder/assets/109468340/59fd7e8b-ba15-4154-8d18-fc9400aff4f1)

**Comment by MehulKhanna** [comment]
> getting this error now: Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 600, in _run_event await coro(*args, **kwargs) File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 48, in on_ready await get_commands(self.bot, self.config.hunting_channel_id) File "/Users/Desktop/PokeGrinder-2.4/cogs/startup.py", line 28, in get_commands for command in await channel.application_commands() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'TextChannel' object has no attribute 'application_commands'
> 
> which is the same error as before, however now my table looks like this: ![image](https://private-user-images.githubusercontent.com/109468340/303139766-59fd7e8b-ba15-4154-8d18-fc9400aff4f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjMyNzYsIm5iZiI6MTcwNzM2Mjk3NiwicGF0aCI6Ii8xMDk0NjgzNDAvMzAzMTM5NzY2LTU5ZmQ3ZThiLWJhMTUtNDE1NC04ZDE4LWZjOTQwMGFmZjRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwMzI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ViYjVmMDYzZmFiN2M4YzlhNjNmNjNhNmU1YTU2YjYwMDE2MzMxNDExMDQ3OTJhY2NkNDg1ZDg2Njc5NWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3m5nbhi3GE4Sqz9gS-RqpnsmImKcthvJ4LL7BXZnqew)

Run these commands and then try:-
```
pip uninstall discord.py-self
```

```
git clone https://github.com/dolfies/discord.py-self
```

```
cd discord.py-self
```

```
python3 -m pip install -U .[voice]
```

**Comment by AloW0304** [comment]
each command works except the final command: python3 -m pip install -U .[voice]
I get the error: zsh: no matches found: .[voice]
Should I use a different shell that's not zsh?

**Comment by AloW0304** [comment]
Nevermind, fixed it. Once again, thank-you so much, it is greatly appreciated

**Comment by Nozmic** [comment]
Hello I am facing this same issue I have followed all the steps above
![image](https://github.com/MehulKhanna/PokeGrinder/assets/118382434/6700e5fb-9164-4e4d-a27f-17e9b9f1cdce)

**Comment by Nozmic** [comment]
Hello I am facing the same issue 
![image](https://github.com/MehulKhanna/PokeGrinder/assets/118382434/c6a6a1ef-9cb5-4015-9bb2-e0e96458cf61)

**Comment by MehulKhanna** [comment]
> Hello I am facing the same issue ![image](https://private-user-images.githubusercontent.com/118382434/305669298-c6a6a1ef-9cb5-4015-9bb2-e0e96458cf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjgxMDcsIm5iZiI6MTcwODIyNzgwNywicGF0aCI6Ii8xMTgzODI0MzQvMzA1NjY5Mjk4LWM2YTZhMWVmLTljYjUtNDAxNS05YmIyLWUwZTk2NDU4Y2Y2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwMzQzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTU1Njg4NTdkYTRjMDJkZDNjY2Y5ZDViMTg0NmQ0NTZmZjc3NTBjNDE1YzA4YWNmYzE2YzI0ZmIyNGVkNTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YeKBDqdU4w9pK_JvagH85wGX7njVic2CAFGcZi1SwnA)

Please check your channel ids in the config. Make sure you can access the channel that you put in the config.

**Comment by Nozmic** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/118382434/1e4753ed-3643-443a-9471-a6fa46bb3a1d)
Now I am getting this error.

Is this how ur supposed to put the channel ID in config?
{
  "ClearConsole": false,
  "CaptchaSolver": true,
  "LoggingInterval": 10,
  "SuspicionAvoidance": 250,
  "abcdtoken": {
    "1088783924xxxxxxxx": 1,
    "10889183148xxxxxxxx": 0,
    "Balls": {
      "Common": "pb",
      "Uncommon": "pb",
      "Rare": "gb",
      "Super Rare": "ub",
      "Legendary": "mb",
      "Shiny": "mb",
      "Shiny Event": "mb",
      "Shiny Full-odds": "prb"
    },

**Comment by Nozmic** [comment]
Oh now it works thanks. But whenever it says "Please wait a few more seconds to find another Pokemon!" the bot stops working and I have to do /pokemon for it to start catching again
