### ISSUE TITLE
Captcha is not working for me

### ISSUE THREAD

**Issue by Atzkaaa** [MehulKhanna/PokeGrinder#43]
It downloads the images in my folder, but it cannot open or read the image I think. I can't see the log in terminal because it desappears to fast.

![image](https://github.com/MehulKhanna/PokeGrinder/assets/61913056/391ba8d4-3a5c-4e03-b46a-b7eab17d688a)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/61913056/6c33d60d-a735-475c-8b2e-c52faf5a28eb)

It says there is no support to this format when i try to open the image

**Comment by MehulKhanna** [comment]
> It downloads the images in my folder, but it cannot open or read the image I think. I can't see the log in terminal because it desappears to fast.
> 
> ![image](https://private-user-images.githubusercontent.com/61913056/304554438-391ba8d4-3a5c-4e03-b46a-b7eab17d688a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMjAxOTQsIm5iZiI6MTcwODAxOTg5NCwicGF0aCI6Ii82MTkxMzA1Ni8zMDQ1NTQ0MzgtMzkxYmE4ZDQtM2E1Yy00ZTAzLWI0NmEtYjdlYWIxN2Q2ODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE3NTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjU1Y2Y2ODQ5NjZiZGQ3MDViNTFiN2RjYWJiNGI2NmE2OTIyNzI4ZDVhMzIzN2NlYjc2ZDIxOGZhYzQxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7hL4QBquJG2ff9rQtjt2C8iiIOwJSPZR1N3n4XJ1Jtk) ![image](https://private-user-images.githubusercontent.com/61913056/304554473-6c33d60d-a735-475c-8b2e-c52faf5a28eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMjAxOTQsIm5iZiI6MTcwODAxOTg5NCwicGF0aCI6Ii82MTkxMzA1Ni8zMDQ1NTQ0NzMtNmMzM2Q2MGQtYTczNS00NzVjLThiMmUtYzUyZmFmNWEyOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE3NTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNDMxYTQ1ZGYxNmRlZmVmYjJiMzY4MzMxOTdlMzlkNTk5NTU5ZWY5Nzc2ODY1NDQyYTZkNWE4N2MzNjQ1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8Dj1MNe3FNWFUD-abMaIqFbEWDxYAFaPfhtGiOsH1w)
> 
> It says there is no support to this format when i try to open the image

I have also started getting issues like this related to captchas now. I have tried many ways to get the captchas to download but none seem to work.

**Comment by MehulKhanna** [comment]
> It downloads the images in my folder, but it cannot open or read the image I think. I can't see the log in terminal because it desappears to fast.
> 
> ![image](https://private-user-images.githubusercontent.com/61913056/304554438-391ba8d4-3a5c-4e03-b46a-b7eab17d688a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzkyNzksIm5iZiI6MTcwODE3ODk3OSwicGF0aCI6Ii82MTkxMzA1Ni8zMDQ1NTQ0MzgtMzkxYmE4ZDQtM2E1Yy00ZTAzLWI0NmEtYjdlYWIxN2Q2ODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE0MDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTI5YzY4MjhlMzYwMGUzOGI2ZjRmZmZjNTI2ODU0OGM4ZjcyNTlkOGIyZTVjODliZDRhNTllMjBkYzJhZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-BqvgtfDGBlkizn0qArrVbAczTdUrDaIyA_LCG7kzc) ![image](https://private-user-images.githubusercontent.com/61913056/304554473-6c33d60d-a735-475c-8b2e-c52faf5a28eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzkyNzksIm5iZiI6MTcwODE3ODk3OSwicGF0aCI6Ii82MTkxMzA1Ni8zMDQ1NTQ0NzMtNmMzM2Q2MGQtYTczNS00NzVjLThiMmUtYzUyZmFmNWEyOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE0MDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjU0OTA3Yzc0ZmI1NjdmMmMyNjg0OGJhODYwNzE4OWFmMzAzMDUyZTY1NDg1OGNiN2FkNjFkZjc1NDE0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gusir78RCLwBuvUAYhD-3v1V1mYYbdjR-G6y0hNfYao)
> 
> It says there is no support to this format when i try to open the image

I have found a possible fix for this. I will commit after more testing.

**Comment by MehulKhanna** [comment]
Please try the latest release. This must be fixed now.
