### ISSUE TITLE
Did not receice response from discord?

### ISSUE THREAD

**Issue by lufy20106** [MehulKhanna/PokeGrinder#44]
**Describe the bug**
loged.
Does not receice response from discord?
stuck
**To Reproduce**
python main.py

**Expected behavior**
Idk

**Screenshots**
![image](https://github.com/MehulKhanna/PokeGrinder/assets/144891766/fe0126b7-e5bb-4c4f-a45c-c53537871018)

**Desktop (please complete the following information):**
 - OS: window
 - Browser waterfox(firefox)
 - Version source

**Additional context**
heh

**Comment by MehulKhanna** [comment]
> **Describe the bug** loged. Does not receice response from discord? stuck **To Reproduce** Steps to reproduce the behavior: python main.py
> 
> **Expected behavior** Idk
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/144891766/304936811-fe0126b7-e5bb-4c4f-a45c-c53537871018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NjgzMDEsIm5iZiI6MTcwNzk2ODAwMSwicGF0aCI6Ii8xNDQ4OTE3NjYvMzA0OTM2ODExLWZlMDEyNmI3LWU1YmItNGM0Zi1hNDVjLWM1MzUzNzg3MTAxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMzMzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTQzZmY2YjcwZTBlODhlNTk1ODk5MzUyZDk4Zjc1NjU2NjdhYmZlNWVjNWQ5NDI3NTBiODM1NzhlYWVlZTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r0T78YBIFgkhbAM683NJ7xbgrV-lX7Ho0ucBCT6_5BI)
> 
> **Desktop (please complete the following information):**
> 
> * OS: window
> * Browser waterfox(firefox)
> * Version source
> 
> **Additional context** heh

This happens when discord doesn't send a response after executing an interaction (buttons and slash commands). This could also be a bug with discord.py-self as I did not experience this with discordgo. This cannot be fixed but this won't cause any problems. I have made it send /pokemon again if there weren't any encounters in the last 30 seconds.

**Comment by lufy20106** [comment]
💀 i will try smt

**Comment by lufy20106** [comment]
bro i found it, idk why but account got banned after not doing anything for 3 weeks 💀

**Comment by MehulKhanna** [comment]
> bro i found it, idk why but account got banned after not doing anything for 3 weeks 💀

Ban from discord or pokemeow?

**Comment by lufy20106** [comment]
pokemeow

**Comment by MehulKhanna** [comment]
> pokemeow

I have found a possible fix for this. I will commit after more testing.

**Comment by MehulKhanna** [comment]
Please try the latest release. This must be fixed now.

**Comment by lufy20106** [comment]
> Please try the latest release. This must be fixed now.

alr 0:24am for me now but ok sure

**Comment by lufy20106** [comment]
Work fine but exeption for “Please wait” still broken

**Comment by MehulKhanna** [comment]
> Work fine but exeption for “Please wait” still broken

Wdym by please wait
