### ISSUE TITLE
 Corrupted or Unusable Captcha Image Downloaded

### ISSUE THREAD

**Issue by wavyboythedude** [MehulKhanna/PokeGrinder#45]
Describe the Bug
When attempting to complete a captcha on Discord using the provided script, the downloaded captcha image appears to be corrupted or unusable.

To Reproduce

Run the script in the command line.
Comes across a captcha in Server.
Allow the script to download the captcha image.
Attempt to open the downloaded captcha image.
Expected Behavior
The downloaded captcha image should be valid and usable for completing the captcha challenge in Discord.
![image](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/fefff3b1-1c4d-4226-bbb3-56aac745c484)
![906716044878](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/2655f31d-f734-4cf9-ab63-f3ed26c1c7cd)

Screenshots
If applicable, attach screenshots of the error message or the corrupted captcha image.

Additional Context

OS: [e.g. Windows 10]
Python Version: [ Python 11]
Discord Client: [ Discord Desktop App, Discord Web Browser]
Captcha Script Version: [latest commit hash or version number]
Any other relevant information or observations about the issue.

**Comment by MehulKhanna** [comment]
> Describe the Bug When attempting to complete a captcha on Discord using the provided script, the downloaded captcha image appears to be corrupted or unusable.
> 
> To Reproduce Steps to reproduce the behavior:
> 
> Run the script in the command line. Comes across a captcha in Server. Allow the script to download the captcha image. Attempt to open the downloaded captcha image. Expected Behavior The downloaded captcha image should be valid and usable for completing the captcha challenge in Discord. ![image](https://private-user-images.githubusercontent.com/160297992/305599475-fefff3b1-1c4d-4226-bbb3-56aac745c484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzkyMTQsIm5iZiI6MTcwODE3ODkxNCwicGF0aCI6Ii8xNjAyOTc5OTIvMzA1NTk5NDc1LWZlZmZmM2IxLTFjNGQtNDIyNi1iYmIzLTU2YWFjNzQ1YzQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNDA4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmE3Nzg2MGEzNTY3NmU1Yjg3MGQ2OTNjZTU5NWViMWVjOTRhYjc4OTcwZjMxNzgwMDRhZTU3ZDcyMDIwNDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FEBTDjOVcMN11NEP2FhUS93PkDSkuVhVQ_t5XI1SiyU) ![906716044878](https://private-user-images.githubusercontent.com/160297992/305599484-2655f31d-f734-4cf9-ab63-f3ed26c1c7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzkyMTQsIm5iZiI6MTcwODE3ODkxNCwicGF0aCI6Ii8xNjAyOTc5OTIvMzA1NTk5NDg0LTI2NTVmMzFkLWY3MzQtNGNmOS1hYjYzLWYzZWQyNmMxYzdjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNDA4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDlmZjBmNWZiYmM5ZmIxMmYyOWE0ZTA1NWZjMWNiNTJlM2UzNTYwYjlmYzlmZDUzZDg5YThkM2Q3ZjQ3ZGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RwVzBKZcIh6o-eXSKQOFXiIthoI6tgOaK_56h-DpzQw)
> 
> Screenshots If applicable, attach screenshots of the error message or the corrupted captcha image.
> 
> Additional Context
> 
> OS: [e.g. Windows 10] Python Version: [ Python 11] Discord Client: [ Discord Desktop App, Discord Web Browser] Captcha Script Version: [latest commit hash or version number] Any other relevant information or observations about the issue.

I have found a possible fix for this. I will commit after more testing.

**Comment by MehulKhanna** [comment]
Please try the latest release. This must be fixed now.

**Comment by wavyboythedude** [comment]
Everything is working now! Thank you for the new release.  
![image](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/077ad341-40c3-412c-99f5-0dbabd313a54)
