### ISSUE TITLE
Super Rod

### ISSUE THREAD

**Issue by wavyboythedude** [MehulKhanna/PokeGrinder#47]
This isn't really a bug but i noticed when you use like super rod it doesn't work not really sure how to work around config too make it work, it's probably going to fast not sure.

![Screenshot 2024-02-18 110152](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/9acdd651-ae3d-4aff-8280-1339411b64a7)

**Comment by MehulKhanna** [comment]
> This isn't really a bug but i noticed when you use like super rod it doesn't work not really sure how to work around config too make it work, it's probably going to fast not sure.
> 
> ![Screenshot 2024-02-18 110152](https://private-user-images.githubusercontent.com/160297992/305736345-9acdd651-ae3d-4aff-8280-1339411b64a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODAxMjIsIm5iZiI6MTcwODI3OTgyMiwicGF0aCI6Ii8xNjAyOTc5OTIvMzA1NzM2MzQ1LTlhY2RkNjUxLWFlM2QtNGFmZi04MjgwLTEzMzk0MTFiNjRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxODEwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGM1MDJiNGVhOTIxNjJmODUyMjI1MjMzNGRhZjg3MGE4MjY5ODNiNjFlNTI2MWU3MmRlNjBkZTI4YTAzNDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ahk7cNTIw60APqPTNXTVrup8nX9JlvEw0Auw3ISONdE)

This is a very tiny little bug.

> This isn't really a bug but i noticed when you use like super rod it doesn't work not really sure how to work around config too make it work, it's probably going to fast not sure.
> 
> ![Screenshot 2024-02-18 110152](https://private-user-images.githubusercontent.com/160297992/305736345-9acdd651-ae3d-4aff-8280-1339411b64a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODAyNjYsIm5iZiI6MTcwODI3OTk2NiwicGF0aCI6Ii8xNjAyOTc5OTIvMzA1NzM2MzQ1LTlhY2RkNjUxLWFlM2QtNGFmZi04MjgwLTEzMzk0MTFiNjRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxODEyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQzOTQ5ZGJmOWFhNTkyMjg0MGMzYThhMTBmZmIyMjA5ZDUwYTFmZWNiMjVmNGFkN2I0NDBhYjdiYTc4NzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ktCzZN7k3bjIVYBsFtolVpBqiK4G822dkv4S_ATLU-A)

This must be fixed now!

**Comment by wavyboythedude** [comment]
It works now thank you again.
