### ISSUE TITLE
Api down error

### ISSUE THREAD

**Issue by SANKETOP** [MehulKhanna/PokeGrinder#50]
![17084215841782971205205369845842](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/b1cba377-e5df-4c70-b368-483f82a1b570)
This error api down

**Comment by lufy20106** [comment]
are u install discord.py-self `using pip install discord.py-self` ?

**Comment by MehulKhanna** [comment]
> ![17084215841782971205205369845842](https://private-user-images.githubusercontent.com/91170563/306209002-b1cba377-e5df-4c70-b368-483f82a1b570.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzAyMDMsIm5iZiI6MTcwODQyOTkwMywicGF0aCI6Ii85MTE3MDU2My8zMDYyMDkwMDItYjFjYmEzNzctZTVkZi00YzcwLWIzNjgtNDgzZjgyYTFiNTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExNTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZmFlMDExZDI5MDdmNjQ2M2JkNTgwYzRjODFiYzk0NzAwYjU0OTA3MzRkOTEzN2Y4OWFjMmMyYjIyYTIzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ALhTxq8MQssUEKaYrJ-5PsNKqLBZfhqEsEZm5wbfQKU) This error api down

Please install discord.py-self as mentioned in the requirements section of the readme.

**Comment by SANKETOP** [comment]
> > ![17084215841782971205205369845842](https://private-user-images.githubusercontent.com/91170563/306209002-b1cba377-e5df-4c70-b368-483f82a1b570.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzAyMDMsIm5iZiI6MTcwODQyOTkwMywicGF0aCI6Ii85MTE3MDU2My8zMDYyMDkwMDItYjFjYmEzNzctZTVkZi00YzcwLWIzNjgtNDgzZjgyYTFiNTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExNTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZmFlMDExZDI5MDdmNjQ2M2JkNTgwYzRjODFiYzk0NzAwYjU0OTA3MzRkOTEzN2Y4OWFjMmMyYjIyYTIzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ALhTxq8MQssUEKaYrJ-5PsNKqLBZfhqEsEZm5wbfQKU) This error api down
> 
> Please install discord.py-self as mentioned in the requirements section of the readme.

![17084393233175330391244329852977](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/54adbacd-58e3-4109-94b1-2033dc92ed53)

**Comment by SANKETOP** [comment]
![17084393711701075911059965569133](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/595982fe-0e3c-4503-bcf9-5df5f631278c)
How I solve this error I have given hunting channel ID

**Comment by SANKETOP** [comment]
![IMG_20240220_200401](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/7ea5d2af-6d04-4a2f-b627-34991d0512b3)
It's not solving captcha and there is nothing showing in terminal about captcha it's only showing encounters

**Comment by SANKETOP** [comment]
I have pasted solver file in assets folder

**Comment by SANKETOP** [comment]
Will I have to run any command for captcha solver to make it work?

**Comment by MehulKhanna** [comment]
> Will I have to run any command for captcha solver to make it work?

Paste your config here please. Hiding tokens.

**Comment by SANKETOP** [comment]
> > Will I have to run any command for captcha solver to make it work?
> 
> Paste your config here please. Hiding tokens.

Ok can I give photo? As I m talking rn from mobile and the config is in pc

**Comment by SANKETOP** [comment]
And also it not encountering anymore after I use /bal or any other command

**Comment by MehulKhanna** [comment]
> > > Will I have to run any command for captcha solver to make it work?
> > 
> > 
> > Paste your config here please. Hiding tokens.
> 
> Ok can I give photo? As I m talking rn from mobile and the config is in pc

Yes you can give photo

**Comment by MehulKhanna** [comment]
> And also it not encountering anymore after I use /bal or any other command

You are not meant to be using any commands in the channel the bot is grinding on.

**Comment by SANKETOP** [comment]
> > And also it not encountering anymore after I use /bal or any other command
> 
> You are not meant to be using any commands in the channel the bot is grinding on.

Oh so any other channel I can try using other commands?

**Comment by MehulKhanna** [comment]
> > > And also it not encountering anymore after I use /bal or any other command
> > 
> > 
> > You are not meant to be using any commands in the channel the bot is grinding on.
> 
> Oh so any other channel I can try using other commands?

Yes.

**Comment by SANKETOP** [comment]
![IMG_20240220_201430](https://github.com/MehulKhanna/PokeGrinder/assets/91170563/38634621-b86a-41db-8e8b-ba19973e2d83)

**Comment by MehulKhanna** [comment]
> ![IMG_20240220_201430](https://private-user-images.githubusercontent.com/91170563/306304196-38634621-b86a-41db-8e8b-ba19973e2d83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA2MDAsIm5iZiI6MTcwODQ0MDMwMCwicGF0aCI6Ii85MTE3MDU2My8zMDYzMDQxOTYtMzg2MzQ2MjEtYjg2YS00MWRiLThlOGItYmExOTk3M2UyZDgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0NDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2Q0MjFkMTEzYmI5M2I3NjJiNmM4Y2E5YWVhMTJlOTcxMGMwYWExNzZjZjVjMDQ3MTY4MWZiNjY4Yzc4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNi6v42Ih0M3qzEeksUwZVnpurMZVr57PU2BQ8AUxMY)

Which command did you use to install discord.py-self?

**Comment by SANKETOP** [comment]
> > ![IMG_20240220_201430](https://private-user-images.githubusercontent.com/91170563/306304196-38634621-b86a-41db-8e8b-ba19973e2d83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA2MDAsIm5iZiI6MTcwODQ0MDMwMCwicGF0aCI6Ii85MTE3MDU2My8zMDYzMDQxOTYtMzg2MzQ2MjEtYjg2YS00MWRiLThlOGItYmExOTk3M2UyZDgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0NDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2Q0MjFkMTEzYmI5M2I3NjJiNmM4Y2E5YWVhMTJlOTcxMGMwYWExNzZjZjVjMDQ3MTY4MWZiNjY4Yzc4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNi6v42Ih0M3qzEeksUwZVnpurMZVr57PU2BQ8AUxMY)
> 
> Which command did you use to install discord.py-self?

The command u have given in readme.md

**Comment by SANKETOP** [comment]
I copy paste it

**Comment by MehulKhanna** [comment]
> I copy paste it

Does anything get printed to the console when a captcha appears?

**Comment by SANKETOP** [comment]
> > I copy paste it
> 
> Does anything get printed to the console when a captcha appears?

Nah

**Comment by SANKETOP** [comment]
Just that encounter and catches one

**Comment by SANKETOP** [comment]
Oh I solve the captcha for 3 times first then Its solving every captcha thx for ur support nice working

**Comment by MehulKhanna** [comment]
> Just that encounter and catches one

Encounters and catches are working fine?

**Comment by SANKETOP** [comment]
> > Just that encounter and catches one
> 
> Encounters and catches are working fine?

Yes fine

**Comment by MehulKhanna** [comment]
> Btw how much time is taken to catch 750 pokemons in one day?

The bot can do 320 encounters per hour.

**Comment by SANKETOP** [comment]
> > Btw how much time is taken to catch 750 pokemons in one day?
> 
> The bot can do 320 encounters per hour.

Oh nearly 2:30 hour

**Comment by SANKETOP** [comment]
For 750 catches

**Comment by SANKETOP** [comment]
I mean encounter

**Comment by MehulKhanna** [comment]
> > > Btw how much time is taken to catch 750 pokemons in one day?
> > 
> > 
> > The bot can do 320 encounters per hour.
> 
> Oh nearly 2:30 hour

Yes

**Comment by SANKETOP** [comment]
Now I tried but when I use command In other channel it's stop encounter and it's spams same encounter and catches panel

**Comment by SANKETOP** [comment]
With same numbers

**Comment by MehulKhanna** [comment]
Then try using commands on a different server.

**Comment by SANKETOP** [comment]
> Then try using commands on a different server.

Ok

**Comment by SANKETOP** [comment]
Tried on other server now it's stopped encountering with did not recieve a response from discord then spam same photo with sam numbers

**Comment by MehulKhanna** [comment]
> Tried on other server now it's stopped encountering with did not recieve a response from discord then spam same photo with sam numbers

This is completely fine as pokemeow has a cooldown of 2 seconds. So when you send a command yourself, the bot might have to suffer from that cooldown.

**Comment by MehulKhanna** [comment]
> > Tried on other server now it's stopped encountering with did not recieve a response from discord then spam same photo with sam numbers
> 
> This is completely fine as pokemeow has a cooldown of 2 seconds. So when you send a command yourself, the bot might have to suffer from that cooldown.

Whenever the bot has an error related to sending commands, it will usually send the commands again after 30 seconds to continue grinding.

**Comment by SANKETOP** [comment]
> > > Tried on other server now it's stopped encountering with did not recieve a response from discord then spam same photo with sam numbers
> > 
> > 
> > This is completely fine as pokemeow has a cooldown of 2 seconds. So when you send a command yourself, the bot might have to suffer from that cooldown.
> 
> Whenever the bot has an error related to sending commands, it will usually send the commands again after 30 seconds to continue grinding.

It's not sending and not continuing grinding

**Comment by SANKETOP** [comment]
After 2 mins also

**Comment by MehulKhanna** [comment]
> After 2 mins also



> After 2 mins also

Run it on colab

**Comment by SANKETOP** [comment]
> > After 2 mins also
> 
> > After 2 mins also
> 
> Run it on colab https://colab.research.google.com/github/MehulKhanna/PokeGrinder/blob/master/assets/PokeGrinder.ipynb

Tried right now it's stopped after sometime in encounter with same numbers and won't work again

**Comment by SANKETOP** [comment]
I mean before 2 to 3 hours
