### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by realphandat** [MehulKhanna/PokeGrinder#51]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/155445899/53295389-72d8-4368-bf55-80ba95174cb8)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/155445899/6a548ef7-6ab8-4ed1-ab9a-acc0262b1306)

**Comment by lufy20106** [comment]
there are no support for prb

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/155445899/306238809-53295389-72d8-4368-bf55-80ba95174cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzAxMDcsIm5iZiI6MTcwODQyOTgwNywicGF0aCI6Ii8xNTU0NDU4OTkvMzA2MjM4ODA5LTUzMjk1Mzg5LTcyZDgtNDM2OC1iZjU1LTgwYmE5NTE3NGNiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMTUwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDZmODdiODdhOTI4MWI5MTgwMzMyODVhYmU3YTcwNmI3MDM1ZTY3YTRmZjliOTkzMTI0MWEwYTU4YTkzMzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9W8MirWgxcG5r2EByAq-Ur7b7udVFPr2rbfEmKcMY48) ![image](https://private-user-images.githubusercontent.com/155445899/306238829-6a548ef7-6ab8-4ed1-ab9a-acc0262b1306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzAxMDcsIm5iZiI6MTcwODQyOTgwNywicGF0aCI6Ii8xNTU0NDU4OTkvMzA2MjM4ODI5LTZhNTQ4ZWY3LTZhYjgtNGVkMS1hYjlhLWFjYzAyNjJiMTMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMTUwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGNmY2ZiODJjZTVhYTZiY2U4MmE2MDlhNDk4NWNiZjkyYjhlMWUwZTQ3ZTQ0YTc5NDFlNzJlYjM0M2IxODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2K0M-jYhMSCZheb_NYDW63zeQOWGdu2AkT5CNlkQaqY)

Please paste the full error here

**Comment by MehulKhanna** [comment]
Also, which version of Python are you using?

**Comment by SANKETOP** [comment]
> Also, which version of Python are you using?

3.11.6

**Comment by MehulKhanna** [comment]
> > Also, which version of Python are you using?
> 
> 3.11.6

Didn't ask you, this is someone else's issue.

**Comment by lufy20106** [comment]
@MehulKhanna im looked in hunting.py there are no prb but have 2 line pokeball?
Why

**Comment by MehulKhanna** [comment]
T

> @MehulKhanna im looked in hunting.py there are no prb but have 2 line pokeball? Why

Auto-buy for prb is not supported since prbs are sometimes not available for purchase in the events shop. There are 2 lines for pokeballs because sometimes pokemeow has a space before the semicolon and sometimes it doesn't. So to be able to buy balls on both cases I have put 2 lines.

![image](https://github.com/MehulKhanna/PokeGrinder/assets/110606617/84bca83f-63aa-4f26-9f3d-7b2d631e9dbd)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/110606617/eaac7beb-40f5-4a97-b808-09cfe0659cd4)

**Comment by MehulKhanna** [comment]
This error must be fixed now. Please download the updated repository again.

**Comment by lufy20106** [comment]
Pokemeow is wired ngl 💀 
If u want to buy prb set the code after some encounter check event shop if have prb buy it and reset if dont just reset

**Comment by lufy20106** [comment]
If u wonder reset what like my old auto ;r d
