### ISSUE TITLE
help

### ISSUE THREAD

**Issue by imkhoa19032110** [MehulKhanna/PokeGrinder#54]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/142767777/1a427610-e6c4-4643-bf8d-ab4c1c905d18)
how to fix this

**Comment by MehulKhanna** [comment]
> ![image](https://private-user-images.githubusercontent.com/142767777/307198928-1a427610-e6c4-4643-bf8d-ab4c1c905d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjQ5ODksIm5iZiI6MTcwODY2NDY4OSwicGF0aCI6Ii8xNDI3Njc3NzcvMzA3MTk4OTI4LTFhNDI3NjEwLWU2YzQtNDY0My1iZjhkLWFiNGMxYzkwNWQxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNTA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDQ5MDY4MWY5NWM4NGU3N2E5NGJmYjgyNTkyNzc5NWRlYjc5YzgzY2I3ZTg2NmFmYzA0MWZhOWNkYzhjNmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gb5uWAAZ3lvfOXqsg3xwFIxJLdfgTbT2OpjIwRukqYY) how to fix this

Your operating system?

**Comment by imkhoa19032110** [comment]
what

**Comment by imkhoa19032110** [comment]
is there a way to fix this

**Comment by MehulKhanna** [comment]
> is there a way to fix this

https://colab.research.google.com/github/MehulKhanna/PokeGrinder/blob/master/assets/PokeGrinder.ipynb

Run the bot here

**Comment by lufy20106** [comment]
ông ý hỏi m dùng hệ điều hành j đó :V
window
linux
macos
...

**Comment by imkhoa19032110** [comment]
> > is there a way to fix this
> 
> https://colab.research.google.com/github/MehulKhanna/PokeGrinder/blob/master/assets/PokeGrinder.ipynb
> 
> Run the bot here

how to save it for every time i open it will save all the data

**Comment by imkhoa19032110** [comment]
> ông ý hỏi m dùng hệ điều hành j đó :V window linux macos ...

t hiểu nhưng do hệ điều hành mà t xài windows lỗi thì chắc ko fix đc r

**Comment by lufy20106** [comment]
> t hiểu nhưng do hệ điều hành mà t xài windows lỗi thì chắc ko fix đc r
giờ muốn save thì cx chịu phải setup lại từ đầu thôi
cái repo của t có cái save đc config

**Comment by lufy20106** [comment]
vô [đây](https://colab.research.google.com/github/lufy20106/PokeGrinder-hm-/blob/master/assets/PokeGrinder.ipynb)
chỉnh config các thứ rồi lưu vô GDrive của m lần sau dùng chỉ cần chạy lệnh thôi ko cần chỉnh config nhớ là phải chạy hết lệnh đấy cả cái config nx

**Comment by imkhoa19032110** [comment]
> > ![image](https://private-user-images.githubusercontent.com/142767777/307198928-1a427610-e6c4-4643-bf8d-ab4c1c905d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjQ5ODksIm5iZiI6MTcwODY2NDY4OSwicGF0aCI6Ii8xNDI3Njc3NzcvMzA3MTk4OTI4LTFhNDI3NjEwLWU2YzQtNDY0My1iZjhkLWFiNGMxYzkwNWQxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNTA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDQ5MDY4MWY5NWM4NGU3N2E5NGJmYjgyNTkyNzc5NWRlYjc5YzgzY2I3ZTg2NmFmYzA0MWZhOWNkYzhjNmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gb5uWAAZ3lvfOXqsg3xwFIxJLdfgTbT2OpjIwRukqYY) how to fix this
> 
> Your operating system?

my operating system is windows 10

**Comment by imkhoa19032110** [comment]
> vô [đây](https://colab.research.google.com/github/lufy20106/PokeGrinder-hm-/blob/master/assets/PokeGrinder.ipynb) chỉnh config các thứ rồi lưu vô GDrive của m lần sau dùng chỉ cần chạy lệnh thôi ko cần chỉnh config nhớ là phải chạy hết lệnh đấy cả cái config nx

t xài mà nó ko vào

**Comment by imkhoa19032110** [comment]
> vô [đây](https://colab.research.google.com/github/lufy20106/PokeGrinder-hm-/blob/master/assets/PokeGrinder.ipynb) chỉnh config các thứ rồi lưu vô GDrive của m lần sau dùng chỉ cần chạy lệnh thôi ko cần chỉnh config nhớ là phải chạy hết lệnh đấy cả cái config nx

**Comment by imkhoa19032110** [comment]
> vô [đây](https://colab.research.google.com/github/lufy20106/PokeGrinder-hm-/blob/master/assets/PokeGrinder.ipynb) chỉnh config các thứ rồi lưu vô GDrive của m lần sau dùng chỉ cần chạy lệnh thôi ko cần chỉnh config nhớ là phải chạy hết lệnh đấy cả cái config nx

m biết cách fix lỗi trên ko với lại run ở colab thì thoát tab có mất ko

**Comment by imkhoa19032110** [comment]
fishshing doesnt work for me although i put it in other channel

**Comment by lufy20106** [comment]
dùng ở server khác nha =)

**Comment by imkhoa19032110** [comment]
> dùng ở server khác nha =)

lmao

**Comment by lufy20106** [comment]
@imkhoa19032110 chạy ổn chx xD

**Comment by imkhoa19032110** [comment]
> @imkhoa19032110 chạy ổn chx xD

chx ổn lắm

**Comment by lufy20106** [comment]
có j nhắn trong discord cho tiện 
lufy20105

**Comment by MehulKhanna** [comment]
Closing as stale and I don't understand anything
