### ISSUE TITLE
uses prb every shiny, fish fish also legendayr

### ISSUE THREAD

**Issue by wavyboythedude** [MehulKhanna/PokeGrinder#56]
Not sure if i did i might have altered something in config, but im pretty sure it uses prb on any fish shiny and also legendary i didn't change config so  i suppose a bug.   
![image](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/a199ae4d-0774-4bd5-a610-b2b3fc473ff0)
![fish go fish](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/7058e428-98c1-4cab-b700-da6697ab35eb)

**Comment by wavyboythedude** [comment]
![Screenshot 2024-02-26 190350](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/71506d95-2fa3-4caf-9192-40726c3b0108)

**Comment by crazystle** [comment]
This is same to me , can you fix it ?

**Comment by MehulKhanna** [comment]
> Not sure if i did i might have altered something in config, but im pretty sure it uses prb on any fish shiny and also legendary i didn't change config so i suppose a bug. ![image](https://private-user-images.githubusercontent.com/160297992/308011313-a199ae4d-0774-4bd5-a610-b2b3fc473ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTc1NzksIm5iZiI6MTcwOTMxNzI3OSwicGF0aCI6Ii8xNjAyOTc5OTIvMzA4MDExMzEzLWExOTlhZTRkLTA3NzQtNGJkNS1hNjEwLWIyYjNmYzQ3M2ZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxODIxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzc3NWEzOTkyMTc0MGM5YjcwZjVmNzczN2U5MzllOTY0ODA5ZjkyMTQ3ZWI1MmI0MzAxNzA2NzIzYjNhOGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9YWZ7QGCBtOI9BHZSYRt8X6FYGiQ8CGJnDjVucj1eDs) ![fish go fish](https://private-user-images.githubusercontent.com/160297992/308011365-7058e428-98c1-4cab-b700-da6697ab35eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTc1NzksIm5iZiI6MTcwOTMxNzI3OSwicGF0aCI6Ii8xNjAyOTc5OTIvMzA4MDExMzY1LTcwNThlNDI4LTk4YzEtNGNhYi1iNzAwLWRhNjY5N2FiMzVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxODIxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Zjc0Zjg5MTg2ZGY2YTg0MzYyZTBkZmFlODU0ZWVhZmZlZDY0MTVhYmY1MTBhZGViOGE4NjJiZWFiZDEwNjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kjJFodmPY5lxBSQAhQqIG_zZmbgP-lTSX5v2UqlcJ1w)

Can you run /fish spawn and send me the screenshot of the message when the pokemon spawns with option to use a ball?

**Comment by wavyboythedude** [comment]
something like this?
![Screenshot 2024-03-01 142416](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/8f7138c5-6c7f-4f14-bbda-7fbe8d9ee291)
****

**Comment by crazystle** [comment]
I set it all rarity to mb but it only use prb if still available , when running out prb it will use ub instead , i dont have pc at the moment ,i will take a creenshot if i come home

**Comment by crazystle** [comment]
> something like this? ![Screenshot 2024-03-01 142416](https://private-user-images.githubusercontent.com/160297992/309394720-8f7138c5-6c7f-4f14-bbda-7fbe8d9ee291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDY5ODcsIm5iZiI6MTcwOTM0NjY4NywicGF0aCI6Ii8xNjAyOTc5OTIvMzA5Mzk0NzIwLThmNzEzOGM1LTZjN2YtNGYxNC1iYmRhLTdmYmU4ZDllZTI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmQ1MDYwNDg5MTIwZGQ2NWIxNGJlM2ZhYmJmNWQzZmUyYjc4NGE4M2U4NzJmYWMxMjgzNWM2YzIzYmY4OGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.23wSiCEtDhatO-B8-VVPw03j4eVaG-hngdgJO22MaNg)

CONFIG #1 : ALL DB 
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/4a14bb64-52ee-4700-a06d-5619a2f0fa07)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/c834a535-3469-458b-8fbb-97833e9ef693)

CONFIG #2 : ALL MB
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/374203c0-9f39-409b-b030-c435490625d2)
when i start with 0 ub it will use gb 
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/60d6053b-70f0-4999-ab65-c781d8a432f2)
when i start with 5 ub it will use ub 
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/ea30d1e4-ccef-411b-8319-4fa052694f34)

CONGIG #3 : it use prb for golden and legendary like kyogre 
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/d353ffe1-8c65-4c8c-9ee7-a20185990b65)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/481452bc-fab9-4b3c-91bc-463a1f9cb101)
![image](https://github.com/MehulKhanna/PokeGrinder/assets/148273656/77d5bad3-add4-420d-9fed-ae223cf37914)

**Comment by MehulKhanna** [comment]
> something like this? ![Screenshot 2024-03-01 142416](https://private-user-images.githubusercontent.com/160297992/309394720-8f7138c5-6c7f-4f14-bbda-7fbe8d9ee291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTY2OTUsIm5iZiI6MTcwOTM1NjM5NSwicGF0aCI6Ii8xNjAyOTc5OTIvMzA5Mzk0NzIwLThmNzEzOGM1LTZjN2YtNGYxNC1iYmRhLTdmYmU4ZDllZTI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNTEzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzY4OWQ0YmQxNzc5ZjUzMTY3YTViODBjYjZkYTE1NGVjMjUzMDNmZWZhZTU5NjI0OWQ1NWZjNTYwYjkzNjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.44ILO_ayQ1mV5PCwloQdJHnETLvELLIS16CVnP-L_Vc)

Thank you, I have found the issue. This will be fixed.

**Comment by MehulKhanna** [comment]
This must be fixed now!

**Comment by wavyboythedude** [comment]
![Screenshot 2024-03-02 114131](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/ae34d9fa-f7f4-4805-95a0-c93ce9722eb5)
it works now thank you very much
