### ISSUE TITLE
Change the rarity of some super rare pokemon

### ISSUE THREAD

**Issue by crazystle** [MehulKhanna/PokeGrinder#57]
Can you add a feature that can config what ball should be use for some special super rare like crystal onix ,this pokemon is so much high and i dont want to miss it .

**Comment by MehulKhanna** [comment]
Done!

**Comment by crazystle** [comment]
> Done!

wow , that so fast , ty

**Comment by crazystle** [comment]
> Done!

Some pokemon have " - " between like crystal-onix ,what shoul i place in config ? Crystal-onix or crystal onix ?

**Comment by MehulKhanna** [comment]
> > Done!
> 
> Some pokemon have " - " between like crystal-onix ,what shoul i place in config ? Crystal-onix or crystal onix ?

The config should have the name that appears in the pokemon spawn message
