### ISSUE TITLE
Finding channels?

### ISSUE THREAD

**Issue by wavyboythedude** [MehulKhanna/PokeGrinder#59]
How to fix this 

![image](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/4fa2e22d-7f1d-4ec1-a953-68b8cdc51a93)

**Comment by MehulKhanna** [comment]
> How to fix this
> 
> ![image](https://private-user-images.githubusercontent.com/160297992/312680915-4fa2e22d-7f1d-4ec1-a953-68b8cdc51a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODcxOTgsIm5iZiI6MTcxMDM4Njg5OCwicGF0aCI6Ii8xNjAyOTc5OTIvMzEyNjgwOTE1LTRmYTJlMjJkLTdmMWQtNGVjMS1hOTUzLTY4YjhjZGM1MWE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMzI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2ZlNmZkYzVmYmQyZjkxYmQyNjJhYmExYjM0NWZlNTI1M2MzOWY3MWZhZTAzNTIzYTVhMmYzZTUwOTZjMGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sAz9HUlbKLeH5jPsFd3G7RHR1qPDtTzpT6owVzpP_7M)

Send full logs please

**Comment by wavyboythedude** [comment]
![image](https://github.com/MehulKhanna/PokeGrinder/assets/160297992/27310c90-00c7-4e4d-a614-495e9e5d1324)
it always shows this everytime i use this account not sure why though

**Comment by wavyboythedude** [comment]
It starts working after  like a minute but i was wondering what it meant.
