### ISSUE TITLE
problem encountered after a fresh install

### ISSUE THREAD

**Issue by Emellane** [MehulKhanna/PokeGrinder#7]
Hello, I encountered this problem after a fresh installation, how to solve this?

![image](https://user-images.githubusercontent.com/98666761/194898434-dfca477a-c54b-49ff-b559-cce210b948f0.png)

Python : python-3.10.7-amd64.exe
Git : Git-2.38.0-64-bit.exe

**Comment by MehulKhanna** [comment]
> Hello, I encountered this problem after a fresh installation, how to solve this?
> 
> ![image](https://user-images.githubusercontent.com/98666761/194898434-dfca477a-c54b-49ff-b559-cce210b948f0.png)
> 
> Python : python-3.10.7-amd64.exe Git : Git-2.38.0-64-bit.exe

Hello, can you please change your discord username so that it only contains standard English alphabets!

**Comment by Emellane** [comment]
after changing username on discord with standard english alphabets!

![image](https://user-images.githubusercontent.com/98666761/194905523-32ca3fb4-9f53-49bd-a1f0-39ab285f6161.png)

**Comment by Emellane** [comment]
I will do this, the problem is that I don't have much money when I launch the game, I am a new player

**Comment by MehulKhanna** [comment]
> I will do this, the problem is that I don't have much money when I launch the game, I am a new player

As a beginner you can replace gb in the config with pb till you have enough coins to buy greatballs! Easiest way to earn coins is to release pokemons after every few catches!

**Comment by Emellane** [comment]
ok thank you for your help I will do that, congratulations for your work
