### ISSUE TITLE
auto battle 

### ISSUE THREAD

**Issue by crazystle** [MehulKhanna/PokeGrinder#78]
Can you suggest me how to add battle feature to the bot, (which file should I start from,....)?

**Comment by MehulKhanna** [comment]
> Can you suggest me how to add battle feature to the bot, (which file should I start from,....)?

I think you should keep auto battle completely seperate from pokegrinder as it is a completely different and a little bit more complex thing.

You can however take ideas on how to structure your project from this repository.

**Comment by MehulKhanna** [comment]
You can start by creating a seperate repository and start your work in there. I will follow your progress and help if you get stuck. Once the auto battle is working fine on its own we can think about merging it with pokegrinder.
