### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by 52gaming** [MehulKhanna/PokeGrinder#8]
Is it possible to change the startup of the bot? It always uses /pokemon 1 second before the cooldown is over. Sorry if this is a dumb question.
![image_2022-10-10_153311577](https://user-images.githubusercontent.com/115509047/194962069-c4108e0f-763a-47a9-89c0-f01f04252931.png)

**Comment by MehulKhanna** [comment]
> Is it possible to change the startup of the bot? It always uses /pokemon 1 second before the cooldown is over. Sorry if this is a dumb question. ![image_2022-10-10_153311577](https://user-images.githubusercontent.com/115509047/194962069-c4108e0f-763a-47a9-89c0-f01f04252931.png)

Currently, in the executable version it is not possible but I will add an option in the config to change that with the next update.

**Comment by 52gaming** [comment]
Thanks! Also, I encounter this error everytime I boot it up. It eventually starts anyways but is it normal?
![image_2022-10-11_161734572](https://user-images.githubusercontent.com/115509047/195215463-4a8a5a4f-10ac-432b-ae40-5c6579bd0f53.png)

**Comment by MehulKhanna** [comment]
> Thanks! Also, I encounter this error everytime I boot it up. It eventually starts anyways but is it normal? It always generates a new folder. ![image_2022-10-11_161734572](https://user-images.githubusercontent.com/115509047/195215463-4a8a5a4f-10ac-432b-ae40-5c6579bd0f53.png)

Yes it is normal

**Comment by MehulKhanna** [comment]
> ![image](https://user-images.githubusercontent.com/115509047/196697048-37a29d8b-cc1e-435b-b738-45dbb5669272.png) ![image](https://user-images.githubusercontent.com/115509047/196697085-35432cb4-25ae-467c-9d6e-1e6f972b72db.png) The cooldown problem is still here, even after I messed with the numbers a little bit. Am I doing something wrong? If this helps, this error shows up every time. ![image](https://user-images.githubusercontent.com/115509047/196697283-896e81b8-da08-40c1-9f4b-9004bb1f18af.png)

I recommend using a 9 second of timer, 0.5 seconds of delay and a 4 second timeout. After changing the options please let me know how frequent is this error.

**Comment by 52gaming** [comment]
The error only happened in 2/8 pokemon summons.

**Comment by 52gaming** [comment]
OH, that makes much more sense. Sorry!

**Comment by 52gaming** [comment]
Sorry for re-opening this thread so much, but is it possible to change how the auto-captcha works? It's good and is accurate most of the time, but when it's not, it uses all five tries up and immediately gets the account banned. I've only had this scenario occur once. I forgot to take a screenshot of the console, but I remember the text going from white to yellow and crashing the bot. Thanks in advance!

**Comment by MehulKhanna** [comment]
> Sorry for re-opening this thread so much, but is it possible to change how the auto-captcha works? It's good and is accurate most of the time, but when it's not, it uses all five tries up and immediately gets the account banned. I've only had this scenario occur once. I forgot to take a screenshot of the console, but I remember the text going from white to yellow and crashing the bot. Thanks in advance!

Thank You for reporting, I will try to recreate this issue.

**Comment by ducpro0211kk** [comment]
![image](https://user-images.githubusercontent.com/65226065/199403334-30a91e4d-7727-4fc1-a840-e64cda0c5b73.png)
![image](https://user-images.githubusercontent.com/65226065/199403475-7b34cda2-5692-49dc-8127-61f89a490d31.png)
I had the same problem and I took a screenshot of it
