### ISSUE TITLE
Fishing does not work

### ISSUE THREAD

**Issue by ManhattanCity** [MehulKhanna/PokeGrinder#82]
**Describe the bug**
Fishing does not work in the sense, /fish command works but after it pulls something out it does not use a ball to catch it and just lets the pokemon run away

**To Reproduce**
1. Just fish

**Expected behavior**
Code has to use the correct ball to catch the pulled pokemon

**Screenshots**
![image](https://github.com/user-attachments/assets/c3a2e5f3-faaa-46d4-a145-16ff5134497a)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Brave

**Comment by MehulKhanna** [comment]
I have updated the repository, it must be fixed now. It was due to inconsistency in Pokemeow's messages. Sometimes it would say "cast out an" and sometimes just "cast an" and sometimes "fished out a wild" and "fished a wild".

**Comment by ManhattanCity** [comment]
Fishing works fine now, thanks.
